# Generated by Django 4.0.1 on 2022-01-12 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='stok',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
